const PRINT_STYLE_ID = "ai-visibility-print-styles"
const PRINT_HEADER_ID = "ai-visibility-print-header"
const PRINT_FOOTER_ID = "ai-visibility-print-footer"

const PRINT_STYLES = `
.ai-visibility-print-header,
.ai-visibility-print-footer {
  display: none;
}

@media print {
  html.ai-visibility-print .ai-visibility-print-header,
  html.ai-visibility-print .ai-visibility-print-footer {
    display: flex !important;
  }

  html.ai-visibility-print .ai-visibility-print-header {
    position: fixed;
    top: 0;
    left: 0;
    right: 0;
    padding: 16px 24px;
    border-bottom: 1px solid #000;
    background: #ffffff;
    z-index: 9999;
    align-items: center;
    justify-content: space-between;
  }

  html.ai-visibility-print .ai-visibility-print-footer {
    position: fixed;
    bottom: 0;
    left: 0;
    right: 0;
    padding: 8px 24px;
    border-top: 1px solid #000;
    background: #ffffff;
    font-size: 11px;
    color: #000000;
    align-items: center;
    justify-content: space-between;
  }

  html.ai-visibility-print .ai-visibility-print-footer .page-number::after {
    content: counter(page);
  }

  html.ai-visibility-print #report-container {
    padding-top: 72px !important;
    padding-bottom: 48px !important;
  }
}

.ai-visibility-print-header .print-title {
  font-size: 16px;
  font-weight: 600;
  color: #000000;
}

.ai-visibility-print-header .print-meta {
  font-size: 12px;
  color: #000000;
  margin-top: 4px;
}

.ai-visibility-print-header .print-domain {
  font-size: 12px;
  color: #000000;
  font-weight: 500;
}
`

function ensurePrintStyles() {
  if (document.getElementById(PRINT_STYLE_ID)) return

  const style = document.createElement("style")
  style.id = PRINT_STYLE_ID
  style.textContent = PRINT_STYLES
  document.head.appendChild(style)
}

function ensureReportHeader(domain?: string) {
  let header = document.getElementById(PRINT_HEADER_ID)
  const container = document.getElementById("report-container")

  if (!header) {
    header = document.createElement("div")
    header.id = PRINT_HEADER_ID
    header.className = "ai-visibility-print-header"
  }

  if (container) {
    if (header.parentElement !== container) {
      container.prepend(header)
    }
  } else if (!header.parentElement) {
    document.body.prepend(header)
  }

  const dateLabel = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "short",
    day: "2-digit",
  })
  const domainLabel = domain && domain.trim() ? domain.trim() : "Not specified"

  header.textContent = ""

  const left = document.createElement("div")
  const title = document.createElement("div")
  title.className = "print-title"
  title.textContent = "BlogSpy AI Visibility Report"
  const meta = document.createElement("div")
  meta.className = "print-meta"
  meta.textContent = `Date: ${dateLabel}`
  left.appendChild(title)
  left.appendChild(meta)

  const right = document.createElement("div")
  right.className = "print-domain"
  right.textContent = `Domain: ${domainLabel}`

  header.appendChild(left)
  header.appendChild(right)
}

function ensureReportFooter() {
  let footer = document.getElementById(PRINT_FOOTER_ID)
  const container = document.getElementById("report-container")

  if (!footer) {
    footer = document.createElement("div")
    footer.id = PRINT_FOOTER_ID
    footer.className = "ai-visibility-print-footer"
  }

  if (container) {
    if (footer.parentElement !== container) {
      container.appendChild(footer)
    }
  } else if (!footer.parentElement) {
    document.body.appendChild(footer)
  }

  footer.textContent = ""

  const left = document.createElement("div")
  left.textContent = "Generated by BlogSpy.io"

  const right = document.createElement("div")
  const label = document.createElement("span")
  label.textContent = "Page "
  const pageNumber = document.createElement("span")
  pageNumber.className = "page-number"

  right.appendChild(label)
  right.appendChild(pageNumber)

  footer.appendChild(left)
  footer.appendChild(right)
}

export function prepareAIVisibilityPrint(options?: { domain?: string }) {
  if (typeof window === "undefined") return

  document.documentElement.classList.add("ai-visibility-print")
  ensurePrintStyles()
  ensureReportHeader(options?.domain)
  ensureReportFooter()

  const cleanup = () => {
    document.documentElement.classList.remove("ai-visibility-print")
  }
  window.addEventListener("afterprint", cleanup, { once: true })
}
