export interface CountryGeo {
  code: string
  name: string
  coordinates: [number, number]
  zoom: number
}

export const ALL_COUNTRIES: CountryGeo[] = [
  { code: "WORLD", name: "Worldwide", coordinates: [0, 20], zoom: 1 },
  { code: "US", name: "United States", coordinates: [-97, 38], zoom: 4 },
  { code: "CA", name: "Canada", coordinates: [-106, 56], zoom: 3 },
  { code: "MX", name: "Mexico", coordinates: [-102, 23], zoom: 5 },
  { code: "GT", name: "Guatemala", coordinates: [-90, 15], zoom: 6 },
  { code: "BZ", name: "Belize", coordinates: [-88.7, 17], zoom: 6 },
  { code: "HN", name: "Honduras", coordinates: [-86.5, 14.5], zoom: 6 },
  { code: "SV", name: "El Salvador", coordinates: [-88.9, 13.8], zoom: 6 },
  { code: "NI", name: "Nicaragua", coordinates: [-85, 13], zoom: 6 },
  { code: "CR", name: "Costa Rica", coordinates: [-84, 10], zoom: 6 },
  { code: "PA", name: "Panama", coordinates: [-80, 8.5], zoom: 6 },
  { code: "CU", name: "Cuba", coordinates: [-79.5, 21.5], zoom: 6 },
  { code: "DO", name: "Dominican Republic", coordinates: [-70.2, 19], zoom: 6 },
  { code: "HT", name: "Haiti", coordinates: [-72.4, 19], zoom: 6 },
  { code: "JM", name: "Jamaica", coordinates: [-77.3, 18.1], zoom: 6 },
  { code: "PR", name: "Puerto Rico", coordinates: [-66.5, 18.2], zoom: 6 },
  { code: "BS", name: "Bahamas", coordinates: [-76, 24], zoom: 6 },
  { code: "BB", name: "Barbados", coordinates: [-59.6, 13.2], zoom: 7 },
  { code: "TT", name: "Trinidad and Tobago", coordinates: [-61.2, 10.5], zoom: 6 },
  { code: "AR", name: "Argentina", coordinates: [-64, -34], zoom: 4 },
  { code: "BR", name: "Brazil", coordinates: [-51, -14], zoom: 4 },
  { code: "CL", name: "Chile", coordinates: [-71, -35], zoom: 4 },
  { code: "CO", name: "Colombia", coordinates: [-74, 4], zoom: 5 },
  { code: "PE", name: "Peru", coordinates: [-75, -9], zoom: 5 },
  { code: "VE", name: "Venezuela", coordinates: [-66, 7], zoom: 5 },
  { code: "EC", name: "Ecuador", coordinates: [-78, -1], zoom: 6 },
  { code: "BO", name: "Bolivia", coordinates: [-64, -17], zoom: 5 },
  { code: "PY", name: "Paraguay", coordinates: [-58, -23], zoom: 5 },
  { code: "UY", name: "Uruguay", coordinates: [-56, -33], zoom: 6 },
  { code: "GY", name: "Guyana", coordinates: [-58, 5], zoom: 6 },
  { code: "SR", name: "Suriname", coordinates: [-56, 4], zoom: 6 },
  { code: "GF", name: "French Guiana", coordinates: [-53, 4], zoom: 6 },
  { code: "GB", name: "United Kingdom", coordinates: [-3, 55], zoom: 6 },
  { code: "IE", name: "Ireland", coordinates: [-8, 53], zoom: 6 },
  { code: "FR", name: "France", coordinates: [2, 46], zoom: 6 },
  { code: "DE", name: "Germany", coordinates: [10, 51], zoom: 6 },
  { code: "ES", name: "Spain", coordinates: [-3.5, 40], zoom: 6 },
  { code: "PT", name: "Portugal", coordinates: [-8, 39.5], zoom: 6 },
  { code: "IT", name: "Italy", coordinates: [12.5, 42.5], zoom: 6 },
  { code: "NL", name: "Netherlands", coordinates: [5.5, 52], zoom: 7 },
  { code: "BE", name: "Belgium", coordinates: [4.5, 50.5], zoom: 7 },
  { code: "CH", name: "Switzerland", coordinates: [8.2, 46.8], zoom: 7 },
  { code: "AT", name: "Austria", coordinates: [14, 47.6], zoom: 7 },
  { code: "DK", name: "Denmark", coordinates: [10, 56], zoom: 7 },
  { code: "NO", name: "Norway", coordinates: [8, 61], zoom: 5 },
  { code: "SE", name: "Sweden", coordinates: [15, 62], zoom: 5 },
  { code: "FI", name: "Finland", coordinates: [26, 64], zoom: 5 },
  { code: "IS", name: "Iceland", coordinates: [-18, 65], zoom: 6 },
  { code: "PL", name: "Poland", coordinates: [19, 52], zoom: 6 },
  { code: "CZ", name: "Czechia", coordinates: [15.5, 49.8], zoom: 7 },
  { code: "SK", name: "Slovakia", coordinates: [19.5, 48.7], zoom: 7 },
  { code: "HU", name: "Hungary", coordinates: [19, 47], zoom: 7 },
  { code: "RO", name: "Romania", coordinates: [25, 46], zoom: 6 },
  { code: "BG", name: "Bulgaria", coordinates: [25, 43], zoom: 6 },
  { code: "GR", name: "Greece", coordinates: [22, 39], zoom: 6 },
  { code: "HR", name: "Croatia", coordinates: [16, 45], zoom: 7 },
  { code: "SI", name: "Slovenia", coordinates: [14.9, 46.1], zoom: 7 },
  { code: "BA", name: "Bosnia and Herzegovina", coordinates: [17.8, 44], zoom: 7 },
  { code: "RS", name: "Serbia", coordinates: [21, 44], zoom: 7 },
  { code: "ME", name: "Montenegro", coordinates: [19.3, 42.7], zoom: 7 },
  { code: "MK", name: "North Macedonia", coordinates: [21.7, 41.6], zoom: 7 },
  { code: "AL", name: "Albania", coordinates: [20, 41], zoom: 7 },
  { code: "EE", name: "Estonia", coordinates: [25, 58.6], zoom: 7 },
  { code: "LV", name: "Latvia", coordinates: [25, 56.9], zoom: 7 },
  { code: "LT", name: "Lithuania", coordinates: [24, 55.2], zoom: 7 },
  { code: "BY", name: "Belarus", coordinates: [28, 53.7], zoom: 6 },
  { code: "UA", name: "Ukraine", coordinates: [31, 49], zoom: 5 },
  { code: "MD", name: "Moldova", coordinates: [28.5, 47], zoom: 7 },
  { code: "RU", name: "Russia", coordinates: [100, 60], zoom: 3 },
  { code: "TR", name: "Turkey", coordinates: [35, 39], zoom: 5 },
  { code: "GE", name: "Georgia", coordinates: [44, 42], zoom: 6 },
  { code: "AM", name: "Armenia", coordinates: [45, 40], zoom: 7 },
  { code: "AZ", name: "Azerbaijan", coordinates: [47, 40.5], zoom: 6 },
  { code: "CY", name: "Cyprus", coordinates: [33, 35], zoom: 7 },
  { code: "IL", name: "Israel", coordinates: [35, 31.5], zoom: 7 },
  { code: "PS", name: "Palestine", coordinates: [35.2, 31.9], zoom: 7 },
  { code: "JO", name: "Jordan", coordinates: [36, 31], zoom: 6 },
  { code: "LB", name: "Lebanon", coordinates: [35.8, 33.9], zoom: 7 },
  { code: "SY", name: "Syria", coordinates: [38, 35], zoom: 6 },
  { code: "IQ", name: "Iraq", coordinates: [44, 33], zoom: 5 },
  { code: "IR", name: "Iran", coordinates: [53, 32], zoom: 4 },
  { code: "SA", name: "Saudi Arabia", coordinates: [45, 24], zoom: 4 },
  { code: "AE", name: "United Arab Emirates", coordinates: [54, 24], zoom: 6 },
  { code: "QA", name: "Qatar", coordinates: [51.2, 25.3], zoom: 7 },
  { code: "KW", name: "Kuwait", coordinates: [47.5, 29.5], zoom: 7 },
  { code: "BH", name: "Bahrain", coordinates: [50.6, 26], zoom: 7 },
  { code: "OM", name: "Oman", coordinates: [55, 21], zoom: 6 },
  { code: "YE", name: "Yemen", coordinates: [47, 15], zoom: 6 },
  { code: "AF", name: "Afghanistan", coordinates: [66, 33], zoom: 5 },
  { code: "PK", name: "Pakistan", coordinates: [69, 30], zoom: 5 },
  { code: "IN", name: "India", coordinates: [78, 22], zoom: 5 },
  { code: "BD", name: "Bangladesh", coordinates: [90, 24], zoom: 6 },
  { code: "LK", name: "Sri Lanka", coordinates: [80.7, 7], zoom: 6 },
  { code: "NP", name: "Nepal", coordinates: [84, 28], zoom: 6 },
  { code: "BT", name: "Bhutan", coordinates: [90.5, 27.5], zoom: 7 },
  { code: "MM", name: "Myanmar", coordinates: [96, 21], zoom: 5 },
  { code: "TH", name: "Thailand", coordinates: [101, 15], zoom: 5 },
  { code: "VN", name: "Vietnam", coordinates: [108, 16], zoom: 5 },
  { code: "KH", name: "Cambodia", coordinates: [105, 12.5], zoom: 6 },
  { code: "LA", name: "Laos", coordinates: [103, 19], zoom: 6 },
  { code: "MY", name: "Malaysia", coordinates: [102, 4], zoom: 6 },
  { code: "SG", name: "Singapore", coordinates: [103.8, 1.35], zoom: 8 },
  { code: "ID", name: "Indonesia", coordinates: [113, -2], zoom: 5 },
  { code: "PH", name: "Philippines", coordinates: [122, 12], zoom: 6 },
  { code: "BN", name: "Brunei", coordinates: [114.9, 4.5], zoom: 7 },
  { code: "TL", name: "Timor-Leste", coordinates: [126, -8.8], zoom: 7 },
  { code: "CN", name: "China", coordinates: [104, 35], zoom: 4 },
  { code: "MN", name: "Mongolia", coordinates: [103, 46], zoom: 5 },
  { code: "KZ", name: "Kazakhstan", coordinates: [67, 48], zoom: 4 },
  { code: "UZ", name: "Uzbekistan", coordinates: [64, 41], zoom: 5 },
  { code: "TM", name: "Turkmenistan", coordinates: [59, 39], zoom: 5 },
  { code: "KG", name: "Kyrgyzstan", coordinates: [75, 41], zoom: 6 },
  { code: "TJ", name: "Tajikistan", coordinates: [71, 38.5], zoom: 6 },
  { code: "JP", name: "Japan", coordinates: [138, 36], zoom: 5 },
  { code: "KR", name: "South Korea", coordinates: [127.5, 36.5], zoom: 6 },
  { code: "KP", name: "North Korea", coordinates: [127, 40], zoom: 6 },
  { code: "TW", name: "Taiwan", coordinates: [121, 23.7], zoom: 7 },
  { code: "HK", name: "Hong Kong", coordinates: [114.2, 22.3], zoom: 8 },
  { code: "MO", name: "Macau", coordinates: [113.5, 22.2], zoom: 8 },
  { code: "AU", name: "Australia", coordinates: [133, -25], zoom: 4 },
  { code: "NZ", name: "New Zealand", coordinates: [174, -41], zoom: 5 },
  { code: "PG", name: "Papua New Guinea", coordinates: [147, -6], zoom: 5 },
  { code: "FJ", name: "Fiji", coordinates: [179, -17.7], zoom: 6 },
  { code: "SB", name: "Solomon Islands", coordinates: [160, -9.5], zoom: 6 },
  { code: "VU", name: "Vanuatu", coordinates: [167, -16], zoom: 6 },
  { code: "NC", name: "New Caledonia", coordinates: [165.5, -21.5], zoom: 6 },
  { code: "WS", name: "Samoa", coordinates: [-172, -13.8], zoom: 6 },
  { code: "TO", name: "Tonga", coordinates: [-175, -21], zoom: 6 },
  { code: "FM", name: "Micronesia", coordinates: [158, 6.9], zoom: 6 },
  { code: "PW", name: "Palau", coordinates: [134.5, 7.5], zoom: 7 },
  { code: "MH", name: "Marshall Islands", coordinates: [171, 7], zoom: 6 },
  { code: "KI", name: "Kiribati", coordinates: [173, 1.8], zoom: 6 },
  { code: "EG", name: "Egypt", coordinates: [30, 26], zoom: 5 },
  { code: "DZ", name: "Algeria", coordinates: [3, 28], zoom: 5 },
  { code: "MA", name: "Morocco", coordinates: [-6, 32], zoom: 5 },
  { code: "TN", name: "Tunisia", coordinates: [10, 34], zoom: 6 },
  { code: "LY", name: "Libya", coordinates: [17, 27], zoom: 5 },
  { code: "SD", name: "Sudan", coordinates: [30, 15], zoom: 5 },
  { code: "SS", name: "South Sudan", coordinates: [31, 7], zoom: 5 },
  { code: "ET", name: "Ethiopia", coordinates: [40, 9], zoom: 5 },
  { code: "ER", name: "Eritrea", coordinates: [39, 15], zoom: 6 },
  { code: "DJ", name: "Djibouti", coordinates: [43.1, 11.8], zoom: 7 },
  { code: "SO", name: "Somalia", coordinates: [46, 5], zoom: 5 },
  { code: "KE", name: "Kenya", coordinates: [37, 0.5], zoom: 5 },
  { code: "UG", name: "Uganda", coordinates: [32, 1.3], zoom: 6 },
  { code: "RW", name: "Rwanda", coordinates: [30, -1.9], zoom: 7 },
  { code: "BI", name: "Burundi", coordinates: [30, -3.4], zoom: 7 },
  { code: "TZ", name: "Tanzania", coordinates: [35, -6], zoom: 5 },
  { code: "CD", name: "Democratic Republic of the Congo", coordinates: [23, -2], zoom: 4 },
  { code: "CG", name: "Republic of the Congo", coordinates: [15, -1], zoom: 6 },
  { code: "GA", name: "Gabon", coordinates: [11.8, -0.5], zoom: 6 },
  { code: "CM", name: "Cameroon", coordinates: [12, 6], zoom: 5 },
  { code: "NG", name: "Nigeria", coordinates: [8, 9], zoom: 5 },
  { code: "GH", name: "Ghana", coordinates: [-1, 7.9], zoom: 6 },
  { code: "CI", name: "Cote d'Ivoire", coordinates: [-5, 7.6], zoom: 6 },
  { code: "SN", name: "Senegal", coordinates: [-14, 14.5], zoom: 6 },
  { code: "ML", name: "Mali", coordinates: [-3.5, 17], zoom: 5 },
  { code: "NE", name: "Niger", coordinates: [9, 17], zoom: 5 },
  { code: "BF", name: "Burkina Faso", coordinates: [-1.5, 12.5], zoom: 6 },
  { code: "BJ", name: "Benin", coordinates: [2.3, 9.3], zoom: 6 },
  { code: "TG", name: "Togo", coordinates: [1.1, 8.5], zoom: 6 },
  { code: "LR", name: "Liberia", coordinates: [-9.5, 6.5], zoom: 6 },
  { code: "SL", name: "Sierra Leone", coordinates: [-11.8, 8.5], zoom: 6 },
  { code: "GN", name: "Guinea", coordinates: [-10.5, 10.5], zoom: 6 },
  { code: "GW", name: "Guinea-Bissau", coordinates: [-15, 12], zoom: 6 },
  { code: "GM", name: "Gambia", coordinates: [-15.4, 13.4], zoom: 7 },
  { code: "CV", name: "Cape Verde", coordinates: [-24, 16], zoom: 6 },
  { code: "MR", name: "Mauritania", coordinates: [-10, 20], zoom: 5 },
  { code: "TD", name: "Chad", coordinates: [18, 15], zoom: 5 },
  { code: "CF", name: "Central African Republic", coordinates: [20.5, 6.5], zoom: 6 },
  { code: "AO", name: "Angola", coordinates: [18, -12], zoom: 5 },
  { code: "NA", name: "Namibia", coordinates: [17, -22], zoom: 5 },
  { code: "BW", name: "Botswana", coordinates: [24, -22], zoom: 6 },
  { code: "ZA", name: "South Africa", coordinates: [24, -29], zoom: 5 },
  { code: "ZW", name: "Zimbabwe", coordinates: [29, -19], zoom: 6 },
  { code: "ZM", name: "Zambia", coordinates: [27, -13], zoom: 5 },
  { code: "MZ", name: "Mozambique", coordinates: [35, -18], zoom: 5 },
  { code: "MW", name: "Malawi", coordinates: [34, -13], zoom: 6 },
  { code: "LS", name: "Lesotho", coordinates: [28.2, -29.6], zoom: 7 },
  { code: "SZ", name: "Eswatini", coordinates: [31.5, -26.5], zoom: 7 },
  { code: "MG", name: "Madagascar", coordinates: [47, -19], zoom: 5 },
  { code: "MU", name: "Mauritius", coordinates: [57.6, -20.2], zoom: 7 },
  { code: "SC", name: "Seychelles", coordinates: [55.4, -4.6], zoom: 7 },
  { code: "KM", name: "Comoros", coordinates: [43.3, -11.8], zoom: 7 },
  { code: "ST", name: "Sao Tome and Principe", coordinates: [6.6, 0.2], zoom: 7 },
]
